const testdata = [
  {
    id: 1,
    quest_name: "งานรับน้อง",
    quest_image: require("../../../assets/images/ActivityTest.jpg"),
    time: "17.00",
    timeEnd: "24.00",
    location: "สร3",
    user_level: "50",
    user_name: "LOLasdasdasdasd",
    user_image: require("../../../assets/images/UserProfileTest.jpg"),
    countParticipant: 2,
    maxParticipant: 30,
  },
  {
    id: 2,
    quest_name: "งานรับพี่",
    quest_image: require("../../../assets/images/KU.jpg"),
    time: "18.00-25.00",
    timeEnd: "5555aaa",
    location: "สร1",
    user_level: "60",
    user_name: "YOOOOO",
    user_image: require("../../../assets/images/UserProfileTest.jpg"),
    countParticipant: 5,
    maxParticipant: 30,
  },
  {
    id: 3,
    quest_name: "งานรับน้อง",
    quest_image: require("../../../assets/images/sorror1.png"),
    time: "19.00-22.00",
    timeEnd: "5555ccc",
    location: "สร2",
    user_level: "70",
    user_name: "WTH",
    user_image: require("../../../assets/images/UserProfileTest.jpg"),
    countParticipant: 7,
    maxParticipant: 30,
  },
];

export default testdata;
